steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/caramel-vim-425013-h0/nwauche-100890276/nwauche-awosemo-yegbe-lamptey:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/caramel-vim-425013-h0/nwauche-100890276/nwauche-awosemo-yegbe-lamptey:$SHORT_SHA'
options:
  logging: 'REGIONAL_USER_OWNED_BUCKET'
